chart-dirs:
  - helm
charts:
  - helm/argo-stack
check-version-increment: false
validate-maintainers: false

# Safe for all helm commands (incl. uninstall)
# helm-extra-args: --timeout 15m

chart-yaml-schema: .ci/chart_schema.yaml
validate-chart-schema: false
lint-conf: .ci/lintconf.yaml

# Only applied to install/upgrade — OK to tweak values here
helm-extra-set-args: >
  --set argo-cd.enabled=false
  --set argocdApplication.enabled=false
  --set ingress.argoWorkflows.enabled=false
  --set ingress.argocd.enabled=false
  --set authzAdapter.replicas=1
  --set s3.enabled=false
  --set argo-workflows.server.enabled=true
  --set argo-workflows.server.secure=false
  --set argo-workflows.server.extraArgs[0]=--auth-mode=server
  --set externalSecrets.enabled=false
  --set externalSecrets.installOperator=false

