---
# ExternalSecret for GitHub token used by GitApp Callback, to post RepoRegistration PR
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.applicationSet.generator.githubTokenSecret.name }}
  namespace: {{ .Values.applicationSet.namespace}}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: argocd
    app.kubernetes.io/part-of: github-generator-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $.Values.externalSecrets.vault.secretStoreName | default "argo-stack-vault" }}
    kind: {{ ternary "ClusterSecretStore" "SecretStore" (eq $.Values.externalSecrets.vault.scope "cluster") }}
  target:
    name: {{ .Values.applicationSet.generator.githubTokenSecret.name }}
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: token
      remoteRef:
        key: {{ include "calypr-projects.vault.extractKey" .Values.applicationSet.generator.githubTokenSecret.vaultPath }}
        property: {{ include "calypr-projects.vault.extractProperty" .Values.applicationSet.generator.githubTokenSecret.vaultPath }}
