#!/usr/bin/env python3
"""
Test script to validate Helm template rendering with repoRegistration.

This test validates that the Helm chart correctly generates all expected
resources from the repoRegistration configuration in my-values.yaml:
- ArgoCD Applications
- ExternalSecrets for GitHub and S3 credentials
- Artifact Repository ConfigMaps
- EventSource for GitHub webhooks
"""

import subprocess
import yaml
import sys
from pathlib import Path
from typing import List, Dict, Any
import pytest

class TestCalyprProjectInitializationRendering:
    """Test suite for initialization template rendering."""
    
    @classmethod
    def setup_class(cls):
        """Set up test environment and render templates."""
        cls.repo_root = Path(__file__).parent.parent
        cls.chart_dir = cls.repo_root / "helm" / "calypr-projects"
        # generated by makefile `make template-calypr-projects-initialize`
        cls.rendered_templates = cls.repo_root / "tests/fixtures/rendered-templates/calypr-projects-initialize-rendered.yaml"
        # Render the template
        cls._read_template()
    
    @classmethod
    def _read_template(cls):
        """Read template output."""
        print(f"\n🔧 Reading Helm template output {cls.rendered_templates}...")

        try:
            with open(cls.rendered_templates, 'r') as f:
                cls.rendered_output = f.read()
            print("✅ Templates read successfully")
        except subprocess.CalledProcessError as e:
            print(f"❌ Failed to read templates: {e.stderr}")
            raise
    
    @classmethod
    def _parse_yaml_documents(cls) -> List[Dict[str, Any]]:
        """Parse the rendered YAML into separate documents."""
        if not cls.rendered_output:
            return []
        
        documents = []
        for doc in yaml.safe_load_all(cls.rendered_output):
            if doc:  # Skip empty documents
                documents.append(doc)
        return documents
    
    @classmethod
    def _filter_by_kind(cls, kind: str) -> List[Dict[str, Any]]:
        """Filter documents by Kubernetes kind."""
        docs = cls._parse_yaml_documents()
        return [doc for doc in docs if doc.get('kind') == kind]
    
    @classmethod
    def _filter_by_label(cls, documents: List[Dict[str, Any]], label_key: str, label_value: str) -> List[Dict[str, Any]]:
        """Filter documents by a specific label."""
        return [
            doc for doc in documents
            if doc.get('metadata', {}).get('labels', {}).get(label_key) == label_value
        ]

    @pytest.mark.parametrize("kind,expected_count", [
        ("Application", 0),
        ("ApplicationSet", 1),
        ("ClusterRole", 1),
        ("ClusterRoleBinding", 1),
        ("ClusterWorkflowTemplate", 1),
        ("ExternalSecret", 1),
        ("WorkflowTemplate", 1),
    ])
    def test_resource_counts(self, kind: str, expected_count: int):
        """Test that expected number of each resource kind is generated."""
        print(f"\n🧪 Testing {kind} count...")

        resources = self._filter_by_kind(kind)
        actual_count = len(resources)

        assert actual_count == expected_count, (
            f"Expected {expected_count} {kind} resource(s), "
            f"but found {actual_count}"
        )
        print(f"✅ Found {actual_count} {kind} resource(s)")


def main():
    """Run all tests and report results."""

    # Run pytest with verbose output
    exit_code = pytest.main([
        __file__,
        '-v',
        '--tb=short',
        '--color=yes'
    ])
    
    return exit_code


if __name__ == '__main__':
    sys.exit(main())
