#!/usr/bin/env python3
"""
Test script to validate Helm template rendering with repoRegistration.

This test validates that the Helm chart correctly generates all expected
resources from the repoRegistration configuration in my-values.yaml:
- ArgoCD Applications
- ExternalSecrets for GitHub and S3 credentials
- Artifact Repository ConfigMaps
- EventSource for GitHub webhooks
"""

import subprocess
import yaml
import sys
from pathlib import Path
from typing import List, Dict, Any
import pytest

class TestCalyprProjectRepoRendering:
    """Test suite for repo template rendering."""
    
    @classmethod
    def setup_class(cls):
        """Set up test environment and render templates."""
        cls.repo_root = Path(__file__).parent.parent
        cls.chart_dir = cls.repo_root / "helm" / "calypr-projects"
        # generated by makefile `make template-calypr-projects-repo`
        cls.rendered_templates = cls.repo_root / "tests/fixtures/rendered-templates/calypr-projects-repo-rendered.yaml"
        # Render the template
        cls._read_template()
    
    @classmethod
    def _read_template(cls):
        """Read template output."""
        print(f"\n🔧 Reading Helm template output {cls.rendered_templates}...")

        try:
            with open(cls.rendered_templates, 'r') as f:
                cls.rendered_output = f.read()
            print("✅ Templates read successfully")
        except subprocess.CalledProcessError as e:
            print(f"❌ Failed to read templates: {e.stderr}")
            raise
    
    @classmethod
    def _parse_yaml_documents(cls) -> List[Dict[str, Any]]:
        """Parse the rendered YAML into separate documents."""
        if not cls.rendered_output:
            return []
        
        documents = []
        for doc in yaml.safe_load_all(cls.rendered_output):
            if doc:  # Skip empty documents
                documents.append(doc)
        return documents
    
    @classmethod
    def _filter_by_kind(cls, kind: str) -> List[Dict[str, Any]]:
        """Filter documents by Kubernetes kind."""
        docs = cls._parse_yaml_documents()
        return [doc for doc in docs if doc.get('kind') == kind]
    
    @classmethod
    def _filter_by_label(cls, documents: List[Dict[str, Any]], label_key: str, label_value: str) -> List[Dict[str, Any]]:
        """Filter documents by a specific label."""
        return [
            doc for doc in documents
            if doc.get('metadata', {}).get('labels', {}).get(label_key) == label_value
        ]

    @pytest.mark.parametrize("kind,expected_count", [
        ("ClusterRoleBinding", 1),
        ("Namespace", 1),
        ("Role", 7),
        ("RoleBinding", 7),
        ("Secret", 1),
        ("Sensor", 1),
        ("ServiceAccount", 1),
        ("WorkflowTemplate", 1),
    ])
    def test_resource_counts(self, kind: str, expected_count: int):
        """Test that expected number of each resource kind is generated."""
        print(f"\n🧪 Testing {kind} count...")

        resources = self._filter_by_kind(kind)
        actual_count = len(resources)

        assert actual_count == expected_count, (
            f"Expected {expected_count} {kind} resource(s), "
            f"but found {actual_count}"
        )
        print(f"✅ Found {actual_count} {kind} resource(s)")

    def test_external_secrets_github_credentials(self):
        """Test that 1 GitHub credential ExternalSecret is generated."""
        print("\n🧪 Testing GitHub credential ExternalSecrets...")
        
        external_secrets = self._filter_by_kind('ExternalSecret')
        repo_reg_secrets = self._filter_by_label(external_secrets, 'source', 'repo-registration')
        github_secrets = self._filter_by_label(repo_reg_secrets, 'secret-type', 'github-credentials')
        
        expected_count = 1
        actual_count = len(github_secrets)
        
        assert actual_count == expected_count, (
            f"Expected {expected_count} GitHub credential ExternalSecret(s), "
            f"but found {actual_count}"
        )
        
        expected_names = {
            'github-secret-nextflow-hello'
        }
        actual_names = {secret['metadata']['name'] for secret in github_secrets}
        
        assert actual_names == expected_names, (
            f"Expected GitHub secrets {expected_names}, but found {actual_names}"
        )
        print(f"✅ Found {actual_count} GitHub credential ExternalSecret(s) with correct names")
    
    def test_external_secrets_s3_credentials(self):
        """Test that 1 S3 credential ExternalSecret is generated."""
        print("\n🧪 Testing S3 credential ExternalSecrets...")
        
        external_secrets = self._filter_by_kind('ExternalSecret')
        repo_reg_secrets = self._filter_by_label(external_secrets, 'source', 'repo-registration')
        
        # Filter for both s3-credentials and s3-data-credentials types
        s3_secrets = [
            secret for secret in repo_reg_secrets
            if secret.get('metadata', {}).get('labels', {}).get('secret-type', '').startswith('s3-')
        ]
        
        expected_count = 1  # 1 artifact bucket only
        actual_count = len(s3_secrets)
        
        assert actual_count == expected_count, (
            f"Expected {expected_count} S3 credential ExternalSecret(s), "
            f"but found {actual_count}"
        )
        
        expected_names = {
            's3-credentials-nextflow-hello-project'
        }
        actual_names = {secret['metadata']['name'] for secret in s3_secrets}
        
        assert actual_names == expected_names, (
            f"Expected S3 secrets {expected_names}, but found {actual_names}"
        )
        print(f"✅ Found {actual_count} S3 credential ExternalSecret(s) with correct names")

    def test_artifact_repository_configmaps_s3_config(self):
        """Test that Artifact Repository ConfigMap has correct S3 configuration."""
        print("\n🧪 Testing Artifact Repository ConfigMap S3 configuration...")
        
        configmaps = self._filter_by_kind('ConfigMap')
        repo_reg_cms = self._filter_by_label(configmaps, 'source', 'repo-registration')
        
        # ConfigMaps are now named "artifact-repositories" and placed in tenant namespaces
        nextflow_cm = next(
            (cm for cm in repo_reg_cms 
             if cm['metadata']['name'] == 'artifact-repositories' 
             and cm['metadata']['namespace'] == 'wf-bwalsh-nextflow-hello-project'),
            None
        )
        assert nextflow_cm is not None, "ConfigMap for nextflow-hello-project not found"
        
        # The data is now under 'default-v1' key instead of 'artifactRepository'
        artifact_repo_yaml = nextflow_cm['data'].get('default-v1')
        assert artifact_repo_yaml is not None, "Missing default-v1 key in ConfigMap data"
        
        artifact_repo = yaml.safe_load(artifact_repo_yaml)
        
        # The hostname, bucket, and region are environment variables, so we just verify structure
        assert 's3' in artifact_repo, "Missing s3 configuration"
        assert 'bucket' in artifact_repo['s3'], "Missing bucket"
        assert 'keyPrefix' in artifact_repo['s3'], "Missing keyPrefix"
        assert artifact_repo['s3']['keyPrefix'] == 'nextflow-hello-project-workflows/', "Incorrect keyPrefix"
        assert 'endpoint' in artifact_repo['s3'], "Missing endpoint"
        assert 'region' in artifact_repo['s3'], "Missing region"
        assert artifact_repo['s3']['insecure'] == True, "Incorrect insecure flag"
        assert artifact_repo['s3']['pathStyle'] == True, "pathStyle should be True"
        
        print("✅ nextflow-hello-project ConfigMap has correct S3 config")

    def test_eventsource_webhook_configurations(self):
        """Test that EventSource has the repository webhook configuration."""
        print("\n🧪 Testing EventSource webhook configurations...")
        
        eventsources = self._filter_by_kind('EventSource')
        repo_reg_eventsources = self._filter_by_label(eventsources, 'source', 'repo-registration')
        
        assert len(repo_reg_eventsources) > 0, "No EventSource found"
        
        eventsource = repo_reg_eventsources[0]
        github_config = eventsource['spec']['github']

        # Validate that the webhook is present
        # The webhook key is expected to be in the format:
        # repo_push-<org>-<repo>
        expected_events = {
            'repo_push-bwalsh-nextflow-hello-project'
        }

        actual_events = set(github_config.keys())
        
        assert actual_events == expected_events, (
            f"Expected webhook events {expected_events}, but found {actual_events}"
        )
        
        # Validate nextflow-hello webhook
        nextflow_webhook = github_config['repo_push-bwalsh-nextflow-hello-project']
        assert nextflow_webhook['owner'] == 'bwalsh', "Incorrect owner for nextflow-hello"
        assert nextflow_webhook['repository'] == 'nextflow-hello-project', "Incorrect repository for nextflow-hello"
        assert 'push' in nextflow_webhook['events'], "Missing push event for nextflow-hello"
        assert nextflow_webhook['active'] == True, "Webhook should be active for nextflow-hello"
        
        print("✅ nextflow-hello-project webhook configured correctly")

    def test_tenant_namespaces_created(self):
        """Test that per-tenant namespace is created with correct naming pattern."""
        print("\n🧪 Testing tenant namespace creation...")
        
        namespaces = self._filter_by_kind('Namespace')
        tenant_namespaces = self._filter_by_label(namespaces, 'calypr.io/workflow-tenant', 'true')
        
        expected_count = 1
        actual_count = len(tenant_namespaces)
        
        assert actual_count == expected_count, (
            f"Expected {expected_count} tenant namespace(s), but found {actual_count}"
        )
        
        # Verify namespace naming pattern: wf-<org>-<repo>
        expected_namespaces = {
            'wf-bwalsh-nextflow-hello-project'
        }
        
        actual_namespaces = {ns['metadata']['name'] for ns in tenant_namespaces}
        
        assert actual_namespaces == expected_namespaces, (
            f"Expected namespaces {expected_namespaces}, but found {actual_namespaces}"
        )
        
        print(f"✅ Found {actual_count} tenant namespace(s) with correct naming pattern")

    def test_tenant_namespaces_have_correct_labels(self):
        """Test that tenant namespaces have required labels."""
        print("\n🧪 Testing tenant namespace labels...")
        
        namespaces = self._filter_by_kind('Namespace')
        tenant_namespaces = self._filter_by_label(namespaces, 'calypr.io/workflow-tenant', 'true')
        
        for ns in tenant_namespaces:
            labels = ns['metadata']['labels']
            
            # Check required labels
            assert 'calypr.io/workflow-tenant' in labels, f"Missing 'calypr.io/workflow-tenant' label in namespace {ns['metadata']['name']}"
            assert labels['calypr.io/workflow-tenant'] == 'true', f"Incorrect value for 'calypr.io/workflow-tenant' in {ns['metadata']['name']}"
            
            assert 'source' in labels, f"Missing 'source' label in namespace {ns['metadata']['name']}"
            assert labels['source'] == 'repo-registration', f"Incorrect 'source' label in {ns['metadata']['name']}"
            
            assert 'app.kubernetes.io/part-of' in labels, f"Missing 'app.kubernetes.io/part-of' label in namespace {ns['metadata']['name']}"
            assert labels['app.kubernetes.io/part-of'] == 'argo-stack', f"Incorrect 'app.kubernetes.io/part-of' in {ns['metadata']['name']}"
        
        print("✅ All tenant namespaces have correct labels")

    def test_tenant_rbac_resources_created(self):
        """Test that RBAC resources are created in each tenant namespace."""
        print("\n🧪 Testing tenant RBAC resources...")
        
        # Get all ServiceAccounts, Roles, and RoleBindings from tenant namespaces
        service_accounts = self._filter_by_kind('ServiceAccount')
        roles = self._filter_by_kind('Role')
        role_bindings = self._filter_by_kind('RoleBinding')
        
        # Filter for repo-registration resources
        tenant_sas = self._filter_by_label(service_accounts, 'source', 'repo-registration')
        tenant_roles = self._filter_by_label(roles, 'source', 'repo-registration')
        tenant_rbs = self._filter_by_label(role_bindings, 'source', 'repo-registration')
        
        # Expected: 1 SA per tenant (1 tenant)
        expected_sa_count = 1
        assert len(tenant_sas) == expected_sa_count, (
            f"Expected {expected_sa_count} ServiceAccount(s) for tenants, but found {len(tenant_sas)}"
        )
        
        # Expected: 3 Roles per tenant (workflow-executor, sensor-workflow-creator, artifact-repository-reader) = 3 total
        expected_role_count = 3
        assert len(tenant_roles) == expected_role_count, (
            f"Expected {expected_role_count} Roles for tenants, but found {len(tenant_roles)}"
        )
        
        # Expected: 3 RoleBindings per tenant = 3 total
        expected_rb_count = 3
        assert len(tenant_rbs) == expected_rb_count, (
            f"Expected {expected_rb_count} RoleBindings for tenants, but found {len(tenant_rbs)}"
        )
        
        # Verify ServiceAccount names
        for sa in tenant_sas:
            assert sa['metadata']['name'] == 'wf-runner', (
                f"ServiceAccount should be named 'wf-runner', but found {sa['metadata']['name']}"
            )
        
        print(f"✅ Found {len(tenant_sas)} ServiceAccount(s), {len(tenant_roles)} Roles, and {len(tenant_rbs)} RoleBindings for tenants")


def main():
    """Run all tests and report results."""

    # Run pytest with verbose output
    exit_code = pytest.main([
        __file__,
        '-v',
        '--tb=short',
        '--color=yes'
    ])
    
    return exit_code


if __name__ == '__main__':
    sys.exit(main())
