apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.argo }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.argocd }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.tenant }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.security }}
