apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextflow-workflow-sa
  namespace: wf-poc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: wf-poc
  name: nextflow-workflow-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextflow-workflow-binding
  namespace: wf-poc
subjects:
- kind: ServiceAccount
  name: nextflow-workflow-sa
  namespace: wf-poc
roleRef:
  kind: Role
  name: nextflow-workflow-role
  apiGroup: rbac.authorization.k8s.io
